rails/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :communities
    resources :users
    resources :curriculums
    resources :speakers do
      collection do
        post :import_csv
        get  :import_page
        get  :export_sample_csv
      end
    end
    resources :stories do
      collection do
        post :import_csv
        get  :export_sample_csv
        get  :import_page
      end
    end
    resources :places do
      collection do
        post :import_csv
        get  :import_page
        get  :export_sample_csv
      end
    end
    resources :curriculum_stories
    resources :themes
    # resources :media_links

    root to: "communities#show"
  end

    delete '/admin/places' => 'places#delete'
    delete '/admin/stories' => 'stories#delete'
    delete '/admin/themes' => 'admin/themes#delete'
    delete '/admin/speakers' => 'admin/speakers#delete'

  scope "(:locale)", locale: Regexp.union(I18n.available_locales.map(&:to_s)) do
    resources :places do
      collection do
        post :import_csv
      end
    end
    resources :stories do
      collection do
        post :import_csv
      end
    end

    devise_for :users, :controllers => { registrations: 'registrations' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'welcome#index'
    get 'home', to: 'home#index', as: "home_map"
    get "search", to: "home#community_search_index", as: "community_search"
    resources :speakers do
      collection do
        post :import_csv
      end
    end
  end
end

rails/app/models/place.rb
class Place < ApplicationRecord
  MEDIA_PATH = Rails.env.test? ? 'spec/fixtures/media' : 'import/media'

  require 'csv'
  belongs_to :community
  has_and_belongs_to_many :stories
  has_one_attached :photo
  validate :photo_format
  validates :lat, numericality: { greater_than_or_equal_to:  -90, less_than_or_equal_to:  90 }, allow_blank: true
  validates :long, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }, allow_blank: true
  has_many :interview_stories, class_name: "Story", foreign_key: "interview_location_id"

  attr_reader :point_geojson

  def self.import_csv(filename, community)
    ApplicationController.helpers.csv_importer(filename, self, community)
  end

  def photo_format
    return unless photo.attached?
    return if photo.blob.content_type.start_with? 'image/'
    photo.purge_later
    errors.add(:photo, 'needs to be an image')
  end

  def photo_url
    if photo.attached?
      Rails.application.routes.url_helpers.rails_blob_path(photo, only_path: true)
    end
  end

  def point_geojson
    RGeo::GeoJSON.encode geojson
  end

  def self.export_sample_csv
    headers = %w{ name type_of_place description region long lat media }

    CSV.generate(headers: true) do |csv|
      csv << headers
    end
  end

  private

  def geojson
    # todo: add extra data here to pass to map about points
    RGeo::GeoJSON::Feature.new(
      RGeo::Cartesian.factory.point(long, lat),
      id,
      name: name,
      description: description,
      region: region,
      type_of_place: type_of_place,
      photo_url: photo_url,
      stories: stories
    )
  end

end

# == Schema Information
#
# Table name: places
#
#  id            :bigint           not null, primary key
#  description   :string
#  lat           :decimal(10, 6)
#  long          :decimal(10, 6)
#  name          :string
#  region        :string
#  type_of_place :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  community_id  :integer
#

rails/app/controllers/admin/places_controller.rb
module Admin
  class PlacesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Place.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Place.find_by!(slug: param)
    # end

    def new
      # ensures that place is built for the current community (so scopes in administrate dashboards work)
      resource = current_community.places.new
      authorize_resource(resource)
      render locals: {
        page: Administrate::Page::Form.new(dashboard, resource),
      }
    end

    def create
      resource = resource_class.new(resource_params)
      # ensures place is created within the current community
      resource.community = current_community
      authorize_resource(resource)

      if resource.save
        redirect_to(
          [namespace, resource],
          notice: translate_with_resource("create.success"),
        )
      else
        render :new, locals: {
          page: Administrate::Page::Form.new(dashboard, resource),
        }
      end
    end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information

    def import_csv
      if params[:file].nil?
        redirect_back(fallback_location: root_path)
        flash[:error] = "No file was attached!"
      else
        filepath = params[:file].read
        errors = Place.import_csv(filepath, current_community)
        errors.empty? ? flash[:notice] = "Places were imported successfully! View them #{view_context.link_to 'here', admin_places_path}." : flash[:error] = errors
        redirect_back(fallback_location: root_path)
      end
    end

    def import_page
      render "import_page"
    end

    def export_sample_csv
      send_data Place.export_sample_csv, filename: "sample_places.csv"
    end
  end
end

rails/app/helpers/places_helper.rb
module PlacesHelper
end

rails/app/views/admin/places/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <% if [:photo].include? attr_name %>
          <th></th>
        <% else %>
          <th class="cell-label
          cell-label--<%= attr_type.html_class %>
          cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
          scope="col"
          role="columnheader"
          aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
          <%= link_to(sanitized_order_params(page, collection_field_name).merge(
            collection_presenter.order_params_for(attr_name, key: collection_field_name)
          )) do %>
          <%= t(
            "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
            default: attr_name.to_s,
          ).titleize %>
              <% if collection_presenter.ordered_by?(attr_name) %>
                <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                  <svg aria-hidden="true">
                    <use xlink:href="#icon-up-caret" />
                  </svg>
                </span>
              <% end %>
            <% end %>
          </th>
        <% end %>
      <% end %>
      <% [valid_action?(:edit, collection_presenter.resource_name),
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          <% if show_action? :show, resource %>
            <%= %(tabindex=0 role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <% if ["photo"].include?(attribute.name) %>
            <td class="cell-data cell-data--<%= attribute.html_class %>">
              <% if resource.photo.attached? %>
                <%= image_tag url_for(resource.photo), height: "50", width: "50" %>
              <% else %>
                <%= image_tag asset_path("home-icon.svg"), height: "50", width: "50" %>
              <% end %>
            </td>
          <% else %>
            <td class="cell-data cell-data--<%= attribute.html_class %>">
              <% if show_action? :show, resource -%>
                <a href="<%= polymorphic_path([namespace, resource]) -%>"
                  tabindex="-1"
                  class="action-show"
                  >
                  <%= render_field attribute %>
                </a>
              <% else %>
                <%= render_field attribute %>
              <% end -%>
            </td>
          <% end %>
        <% end %>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) if show_action? :edit, resource%></td>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.destroy"),
            [namespace, resource],
            class: "text-color-red",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
          ) if show_action? :destroy, resource %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

rails/app/views/admin/places/import_page.html.erb
<section class="main-content__body padding-fix color-fix">
  <p>
    IMPORTANT: Need to import places? The values in your csv must be in a particular order. Feel free to use this <%= link_to "SAMPLE CSV", export_sample_csv_admin_places_path %> to get started with successfully uploading places.
  </p>

  <%= form_tag send("import_csv_admin_places_path"), multipart: true do %>
    <div class=form>
      <div class="form-group color-fix">
        <label class="form-title" for="file"><%= t("administrate.file_to_update") %></label>
          <%= file_field_tag :file, :accept => 'text/csv', class: "form-control-file file-update import-file-btn" %>
      </div>
      <div class="form-group">
          <%= button_tag :class => "btn-import new-button",
                :data => {
                :disable_with => 'Uploading your file...',
                } do %>
          <i class="fa fa-upload import-icon"></i><%= t("administrate.import_button", resource: t("administrate.places")) %>
        <% end %>
        <i class="fa fa-spinner fa-spin fa-lg import-spinner"></i>
      </div>
    </div>
  <% end %>
</section>

rails/app/views/admin/places/index.html.erb
<%#
# Index

This view is the template for the index page.
It is responsible for rendering the search bar, header and pagination.
It renders the `_table` partial to display details about the resources.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Collection][1].
  Contains helper methods to help display a table,
  and knows which attributes should be displayed in the resource's table.
- `resources`:
  An instance of `ActiveRecord::Relation` containing the resources
  that match the user's search criteria.
  By default, these resources are passed to the table partial to be displayed.
- `search_term`:
  A string containing the term the user has searched for, if any.
- `show_search_bar`:
  A boolean that determines if the search bar should be shown.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<% content_for(:title) do %>
  <%= t("administrate.#{page.resource_name.pluralize}") %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title color-fix title-underline" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <% if show_search_bar %>
    <%= render(
      "shared/search",
      search_term: search_term,
      resource_name: t("administrate.#{page.resource_name.pluralize}"),
      per_page: params[:per_page]
    ) %>
  <% end %>

  <div>
    <%= link_to(
            t(
                "administrate.actions.new_resource",
                name: t("administrate.#{page.resource_name}")
            ),
            [:new, namespace, page.resource_path.to_sym],
            class: "button new-button",
        ) if valid_action?(:new) && show_action?(:new, new_resource) %>
  </div>
</header>

<section class="main-content__body main-content__body--flush padding-fix color-fix">
  <div class="table-wrapper">
    <%= render(
            "collection",
            collection_presenter: page,
            collection_field_name: resource_name,
            page: page,
            resources: resources,
            table_title: "page-title",
        ) %>

    <%= paginate resources, param_name: '_page' %>
  </div>
  <div class="table-underline"></div>
</section>

<section>
  <div>
    <%= link_to 'Import',
    page.resource_name.pluralize + '/import_page',
    class: 'button'
    %>
  </div>
</section>

rails/app/views/admin/places/show.html.erb
<%#
# Show

This view is the template for the show page.
It renders the attributes of a resource,
as well as a link to its edit page.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Show][1].
  Contains methods for accessing the resource to be displayed on the page,
  as well as helpers for describing how each attribute of the resource
  should be displayed.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Show
%>

<% content_for(:title) { page.page_title } %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <small><%= t("place") %></small><br />
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to(
      t("administrate.actions.edit_resource", name: page.page_title),
      [:edit, namespace, page.resource],
      class: "button",
    ) if valid_action?(:edit) && show_action?(:edit, page.resource) %>
  </div>
</header>

<section class="main-content__body main-content__body--split">
  <% if page.resource.photo.attached? %>
    <%= image_tag url_for(page.resource.photo) %>
  <% else %>
    <%= image_tag asset_path("speaker.png") %>
  <% end %>
  <dl>
    <dt class="attribute-label">
      <%= t("helpers.label.#{page.resource_name}.#{:name}") %>
    </dt>
    <dd class="attribute-data">
      <%= page.resource.name %>
    </dd>
    <dt class="attribute-label">
      <%= t("helpers.label.#{page.resource_name}.#{:description}") %>
    </dt>
    <dd class="attribute-data">
      <%= page.resource.description %>
    </dd>
    <dt class="attribute-label">
      <%= t("helpers.label.#{page.resource_name}.#{:region}") %>
    </dt>
    <dd class="attribute-data">
      <%= page.resource.region %>
    </dd>
    <dt class="attribute-label">
      <%= t("helpers.label.#{page.resource_name}.#{:type_of_place}") %>
    </dt>
    <dd class="attribute-data">
      <%= page.resource.type_of_place %>
    </dd>
    <dt class="attribute-label">
      <%= t("helpers.label.#{page.resource_name}.#{:region}") %>
    </dt>
    <dd class="attribute-data">
      <%= page.resource.region %>
    </dd>
  </dl>
</section>

<section class="main-content__body">
  <h2><%= t("administrate.stories") %> at <%= page.resource.name %></h2>
  <div class="cards">
    <% page.resource.stories.each do |story| %>
      <div class="cards__item">
        <div>
        <h4 class="cards__item--title"><%= story.title %></h4>
        <%= story.desc %>
        </div>
        <div>
          <%= link_to t("administrate.actions.show_resource", name: nil), admin_story_path(story), class: "button" %>
        </div>
      </div>
    <% end %>
  </div>
</section>