rails/config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :communities
    resources :users
    resources :curriculums
    resources :speakers do
      collection do
        post :import_csv
        get  :import_page
        get  :export_sample_csv
      end
    end
    resources :stories do
      collection do
        post :import_csv
        get  :export_sample_csv
        get  :import_page
      end
    end
    resources :places do
      collection do
        post :import_csv
        get  :import_page
        get  :export_sample_csv
      end
    end
    resources :curriculum_stories
    resources :themes
    # resources :media_links

    root to: "communities#show"
  end

    delete '/admin/places' => 'places#delete'
    delete '/admin/stories' => 'stories#delete'
    delete '/admin/themes' => 'admin/themes#delete'
    delete '/admin/speakers' => 'admin/speakers#delete'

  scope "(:locale)", locale: Regexp.union(I18n.available_locales.map(&:to_s)) do
    resources :places do
      collection do
        post :import_csv
      end
    end
    resources :stories do
      collection do
        post :import_csv
      end
    end

    devise_for :users, :controllers => { registrations: 'registrations' }
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'welcome#index'
    get 'home', to: 'home#index', as: "home_map"
    get "search", to: "home#community_search_index", as: "community_search"
    resources :speakers do
      collection do
        post :import_csv
      end
    end
  end
end

rails/app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    include Administrate::Punditize

    before_action :authenticate_user!

    before_action :set_locale
    before_action :set_community
    before_action :can_view_list?, only: :index
    before_action :can_view_show?, only: :show

    rescue_from Pundit::NotAuthorizedError, with: :not_authorized

    def default_url_options
      { locale: I18n.locale }
    end

    private

    def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end

    def not_authorized
      flash.alert = "You are not authorized to perform this action"
      redirect_to admin_root_path
    end

    def set_community
      @_community ||= current_user.community
    end

    helper_method def current_community
      @_community
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end

    # by default, Punditize with Administrate does not policy on index views.
    # this ensures we check that list views are utilizing the Pundit policies
    def can_view_list?
      authorize resource_name, :index?
    end

    # by default, Punditize with Administrate does not policy on show views.
    # this ensures we check that list views are utilizing the Pundit policies
    def can_view_show?
      authorize resource_name, :show?
    end
  end
end

rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery

  before_action :authenticate_user!
  before_action :set_locale
  before_action :set_community

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def default_url_options
    { locale: I18n.locale }
  end

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def set_community
    # skip if user is not authenticated
    return unless current_user

    @community ||= current_user.community
  end

  def current_community
    @community
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
end

rails/app/helpers/application_helper.rb
module ApplicationHelper
  def application_locales(request_path: nil)
    locales = I18n.available_locales.sort.map do |locale|
      locale_identifier = locale == I18n.locale ? "#{locale} (#{t("selected_language")}) " : locale
      link_to locale_identifier, link_to_with_locale(locale, request_path: request_path), class: "language-color"
    end
    safe_join(locales, " | ".html_safe)
  end

  def link_to_with_locale(locale, request_path: nil)
    if request_path.present?
      maybe_locale, path = request_path[1..-1].split("/", 2)
      if I18n.available_locales.include?(maybe_locale.to_sym)
        "/#{locale}/#{path}"
      else
        "/#{locale}#{request_path}"
      end
    else
      root_path(locale: locale)
    end
  end
end

rails/app/views/admin/application/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
          <%= link_to(sanitized_order_params(page, collection_field_name).merge(
            collection_presenter.order_params_for(attr_name, key: collection_field_name)
          )) do %>
            <%= t("administrate.table_columns.#{collection_field_name}.#{attr_name}") %>
            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <% [valid_action?(:edit, collection_presenter.resource_name),
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          tabindex="0"
          <% if valid_action? :show, collection_presenter.resource_name %>
            <%= %(role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 class="action-show"
                 >
                <%= render_field attribute rescue nil %>
              </a>
            <% end -%>
          </td>
        <% end %>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) if show_action? :edit, resource%></td>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.destroy"),
            [namespace, resource],
            class: "text-color-red",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
          ) if show_action? :destroy, resource %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

rails/app/views/admin/application/_flashes.html.erb
<%#
# Flash Partial

This partial renders flash messages on every page.

## Relevant Helpers:

- `flash`:
  Returns a hash,
  where the keys are the type of flash (alert, error, notice, etc)
  and the values are the message to be displayed.
%>

<% if flash.any? %>
  <div class="flashes">
    <% flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
      <% if value.instance_of? String %>
        <%= value.html_safe %> 
      <% else %>
        <% value.each do |line_number, error_array| %>
          <b><%= line_number %></b>
          <ul>
            <% error_array.each do |e| %>
              <li>
                <%= e.html_safe %>
              </li>
            <% end %>
          </ul>
        <% end %>
      <% end %>
      </div>
    <% end -%>
  </div>
<% end %>

rails/app/views/admin/application/_navigation.html.erb
<%#
# Navigation
This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<header class="header--main">
  <h1>
    <%= link_to admin_root_path do %>
      <%= image_tag "logocombo.svg", alt: "Terrastories", class: "header--logo" %>
    <% end %>
  </h1>
  <nav class="navigation" role="navigation">
    <ul>
      <% if current_user.super_admin %>
        <li><%= link_to t("administrate.communities"), admin_communities_path %></a></li>
        <li>
          <a href="javascript:void(0);"><%= current_user.email %> <i class="fa fa-angle-down"></i></a>
          <ul class="dropdown" aria-label="submenu">
            <% if current_user.super_admin %>
            <% end %>
            <li><%= link_to t("profile"), edit_admin_user_path(current_user) %></a></li>
            <li><%= link_to t("logout"), destroy_user_session_path, method: :delete  %></li>
          </ul>
        </li>
      <% else %>
        <% if current_user.admin? || current_user.editor? %>
          <li><%= link_to t("administrate.speakers"), admin_speakers_path %></a></li>
          <li><%= link_to t("administrate.stories"), admin_stories_path %></a></li>
          <li><%= link_to t("administrate.places"), admin_places_path %></a></li>
        <% end %>
        <% if current_user.admin? %>
          <li>
            <a href="javascript:void(0);"><%= t("administrate.community") %> <i class="fa fa-angle-down"></i></a >
            <ul class="dropdown" aria-label="submenu">
              <li><%= link_to t("administrate.users"), admin_users_path %></a></li>
              <li><%= link_to t("administrate.theme"), admin_theme_path(current_community.theme)  %></li>
            </ul>
          </li>
        <% end %>
        <li>
          <a href="javascript:void(0);"><%= current_user.email %> <i class="fa fa-angle-down"></i></a>
          <ul class="dropdown" aria-label="submenu">
            <% if current_user.super_admin %>
              <li><%= link_to t("administrate.communities"), admin_communities_path %></a></li>
            <% end %>
            <li><%= link_to t("profile"), edit_admin_user_path(current_user) %></a></li>
            <li><%= link_to t("logout"), destroy_user_session_path, method: :delete  %></li>
          </ul>
        </li>
        <li class="navigation__last-menu-item">
          <%= link_to(t("administrate.navigation.back_to_app"), home_map_path(locale: params[:locale])) if defined?(root_url) %>
        </li>
      <% end %>
    </ul>
  </nav>
</header>